host: "localhost"
user: "root"
password: "gAAAAABij43fmytcza2S34qdwBxP8UiwVJbu8JhriTjATZNDurRFnb1xgtQw2QfIDEKsXMHACTB3xBf8OS0fsbYlIxCDLefEPAelb_HtUCcmgKm_Ch_bIbkcG9eB6dHJ3f_6hYhbuc9VMrmI4AMfsAbD-he5Y4QyWnszf3bBhsidEqiHvfIzDvvdh9x5Fb_kGKgHJMPYIi0k-J7bVdiRbDP2bGlIPFBgqTs84qxdzMy5Tjeo46X6eRK1UWurjMi6iwqj0bACiY6-Z35YOGhhrl6TiDf61IcL5eDHgMwxZnMHkKT-ZkSKcofGO4DSor5hIYHf6daSkaIFcJ-Gr8GykqXeK5Srk02lFKyV52OCnQAjX9WCVue6lLdvvivfjLLa42KCDYVBPjPl"
db_name: "sakila"
auto_commit_flag: true
cursor_type: "dict"
secret: "secret/secret.key"